#############################################################################
# Makefile for building: perfect_pitch
# Generated by qmake (3.1) (Qt 6.8.2)
# Project:  perfect_pitch.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile perfect_pitch.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DPPALSA -DPORTAUDIO -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/i386-linux-gnu/qt6 -I/usr/include/i386-linux-gnu/qt6/QtWidgets -I/usr/include/i386-linux-gnu/qt6/QtGui -I/usr/include/i386-linux-gnu/qt6/QtCore -I. -I. -I/usr/lib/i386-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = perfect_pitch1.0.0
DISTDIR = /home/pi/development/perfect_pitch.test/.tmp/perfect_pitch1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/i386-linux-gnu
LIBS          = $(SUBLIBS) -lasound -lm -lportaudio /usr/lib/i386-linux-gnu/libQt6Widgets.so /usr/lib/i386-linux-gnu/libQt6Gui.so /usr/lib/i386-linux-gnu/libGLX.so /usr/lib/i386-linux-gnu/libOpenGL.so /usr/lib/i386-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		kde_ui.cpp \
		ppwidget.cpp \
		ppstatusbar.cpp \
		worker.cpp \
		utils.c \
		perfect_pitch.c \
		unix_sound.c moc_kde_ui.cpp \
		moc_ppwidget.cpp \
		moc_ppstatusbar.cpp
OBJECTS       = main.o \
		kde_ui.o \
		ppwidget.o \
		ppstatusbar.o \
		worker.o \
		utils.o \
		perfect_pitch.o \
		unix_sound.o \
		moc_kde_ui.o \
		moc_ppwidget.o \
		moc_ppstatusbar.o
DIST          = /usr/lib/i386-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/permissions.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/lex.prf \
		perfect_pitch.pro kde_ui.h \
		ppwidget.h \
		utils.h \
		perfect_pitch.h \
		unix_sound.h \
		ppstatusbar.h main.cpp \
		kde_ui.cpp \
		ppwidget.cpp \
		ppstatusbar.cpp \
		worker.cpp \
		utils.c \
		perfect_pitch.c \
		unix_sound.c
QMAKE_TARGET  = perfect_pitch
DESTDIR       = 
TARGET        = perfect_pitch


first: all
####### Build rules

perfect_pitch: ui_perfect_pitch.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: perfect_pitch.pro /usr/lib/i386-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/i386-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/permissions.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt6/mkspecs/features/lex.prf \
		perfect_pitch.pro \
		/usr/lib/i386-linux-gnu/libQt6Widgets.prl \
		/usr/lib/i386-linux-gnu/libQt6Gui.prl \
		/usr/lib/i386-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile perfect_pitch.pro
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/permissions.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/i386-linux-gnu/qt6/mkspecs/features/lex.prf:
perfect_pitch.pro:
/usr/lib/i386-linux-gnu/libQt6Widgets.prl:
/usr/lib/i386-linux-gnu/libQt6Gui.prl:
/usr/lib/i386-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile perfect_pitch.pro

qmake_all: FORCE


all: Makefile perfect_pitch

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/i386-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents kde_ui.h ppwidget.h utils.h perfect_pitch.h unix_sound.h ppstatusbar.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp kde_ui.cpp ppwidget.cpp ppstatusbar.cpp worker.cpp utils.c perfect_pitch.c unix_sound.c $(DISTDIR)/
	$(COPY_FILE) --parents perfect_pitch.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/i386-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/i386-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_kde_ui.cpp moc_ppwidget.cpp moc_ppstatusbar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_kde_ui.cpp moc_ppwidget.cpp moc_ppstatusbar.cpp
moc_kde_ui.cpp: kde_ui.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pi/development/perfect_pitch.test/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pi/development/perfect_pitch.test -I/usr/include/i386-linux-gnu/qt6 -I/usr/include/i386-linux-gnu/qt6/QtWidgets -I/usr/include/i386-linux-gnu/qt6/QtGui -I/usr/include/i386-linux-gnu/qt6/QtCore -I/usr/include/c++/14 -I/usr/include/i386-linux-gnu/c++/14 -I/usr/include/c++/14/backward -I/usr/lib/gcc/i686-linux-gnu/14/include -I/usr/local/include -I/usr/include/i386-linux-gnu -I/usr/include kde_ui.h -o moc_kde_ui.cpp

moc_ppwidget.cpp: ppwidget.h \
		utils.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pi/development/perfect_pitch.test/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pi/development/perfect_pitch.test -I/usr/include/i386-linux-gnu/qt6 -I/usr/include/i386-linux-gnu/qt6/QtWidgets -I/usr/include/i386-linux-gnu/qt6/QtGui -I/usr/include/i386-linux-gnu/qt6/QtCore -I/usr/include/c++/14 -I/usr/include/i386-linux-gnu/c++/14 -I/usr/include/c++/14/backward -I/usr/lib/gcc/i686-linux-gnu/14/include -I/usr/local/include -I/usr/include/i386-linux-gnu -I/usr/include ppwidget.h -o moc_ppwidget.cpp

moc_ppstatusbar.cpp: ppstatusbar.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pi/development/perfect_pitch.test/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pi/development/perfect_pitch.test -I/usr/include/i386-linux-gnu/qt6 -I/usr/include/i386-linux-gnu/qt6/QtWidgets -I/usr/include/i386-linux-gnu/qt6/QtGui -I/usr/include/i386-linux-gnu/qt6/QtCore -I/usr/include/c++/14 -I/usr/include/i386-linux-gnu/c++/14 -I/usr/include/c++/14/backward -I/usr/lib/gcc/i686-linux-gnu/14/include -I/usr/local/include -I/usr/include/i386-linux-gnu -I/usr/include ppstatusbar.h -o moc_ppstatusbar.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_perfect_pitch.h
compiler_uic_clean:
	-$(DEL_FILE) ui_perfect_pitch.h
ui_perfect_pitch.h: perfect_pitch.ui \
		/usr/lib/qt6/libexec/uic \
		ppwidget.h \
		ppstatusbar.h \
		utils.h
	/usr/lib/qt6/libexec/uic perfect_pitch.ui -o ui_perfect_pitch.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp utils.h \
		ui_perfect_pitch.h \
		ppstatusbar.h \
		ppwidget.h \
		kde_ui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

kde_ui.o: kde_ui.cpp ui_perfect_pitch.h \
		ppstatusbar.h \
		ppwidget.h \
		utils.h \
		kde_ui.h \
		worker.h \
		unix_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kde_ui.o kde_ui.cpp

ppwidget.o: ppwidget.cpp utils.h \
		ui_perfect_pitch.h \
		ppstatusbar.h \
		ppwidget.h \
		kde_ui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ppwidget.o ppwidget.cpp

ppstatusbar.o: ppstatusbar.cpp ppstatusbar.h \
		utils.h \
		unix_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ppstatusbar.o ppstatusbar.cpp

worker.o: worker.cpp utils.h \
		worker.h \
		unix_sound.h \
		perfect_pitch.h \
		ui_perfect_pitch.h \
		ppstatusbar.h \
		ppwidget.h \
		kde_ui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o worker.o worker.cpp

utils.o: utils.c utils.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o utils.o utils.c

perfect_pitch.o: perfect_pitch.c utils.h \
		unix_sound.h \
		perfect_pitch.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o perfect_pitch.o perfect_pitch.c

unix_sound.o: unix_sound.c utils.h \
		unix_sound.h \
		perfect_pitch.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o unix_sound.o unix_sound.c

moc_kde_ui.o: moc_kde_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kde_ui.o moc_kde_ui.cpp

moc_ppwidget.o: moc_ppwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ppwidget.o moc_ppwidget.cpp

moc_ppstatusbar.o: moc_ppstatusbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ppstatusbar.o moc_ppstatusbar.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

